### ISSUE TITLE
ERROR: Cannot install chainlit==1.0.401 and literalai==0.0.606 because these package versions have conflicting dependencies. 

### ISSUE THREAD

**Issue by jayita13** [Chainlit/literalai-cookbooks#19]
The conflict is caused by:     
The user requested literalai==0.0.606    
 chainlit 1.0.401 depends on literalai==0.0.300

**Comment by desaxce** [comment]
Hi @jayita13 Can you please share with us which cookbook you are trying to run? 

It looks like you have an already installed `chainlit` package, and that you want to run a cookbook based on a more recent version of `literalai`. Since `chainlit` is not needed to run any of the cookbooks, I suggest you install requirements in a separate pyenv / conda environment.
